# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
# GITHUB_REF_NAME (github.ref_name)- branch or tag that triggerred the workflow
# GITHUB_SHA (github.sha) - sha that triggerred the workflow
# GITHUB_REPOSITORY (github.repository) - owner/repo name
# GITHUB_REPOSITORY_OWNER (github.repository_owner) - owner only name
# GITHUB_EVENT_NAME (github.event_name) - name of event that triggered this
# usage ${THE-GITHUB-VAR}
name: Lint Check

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      cmd:
        description: 'lint for now'
        default: 'lint'
        required: true
      tag:
        description: 'Enter branch or tag'
        default: 'main'
        required: true
  issue_comment:
    types: [created]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  TAG: ${{ github.event.inputs.tag || 'main' }}
  COMMAND: ${{ github.event.inputs.cmd || 'lint' }}

# each job run in parallel by default
jobs:
  lint: # job
    # needs: <job name of job required to succeed to run this job>
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # one if per job
    steps:
      - name: DEBUG: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash
    steps:
      - name: Do this
        run: |
          echo ${{ github.repository }} ${GITHUB_REPOSITORY}
          echo ${{ github.repository_owner }} ${GITHUB_REPOSITORY_OWNER}
          echo ${{ github.ref_name }} ${GITHUB_REF_NAME}
          echo ${{ github.event_name }} ${GITHUB_EVENT_NAME}
    # if: (github.event.issue.pull_request && startsWith(github.event.comment.body, '/lint')) || github.event_name == 'workflow_dispatch'
    # steps:
    #   - name: Selected Branch/tag
    #     run: echo ${{ github.event.inputs.tag }}
    #   - name: Checkout Repository
    #     uses: actions/checkout@v3
    #     with:
    #       ref: ${{ github.event.inputs.tag }}
    #   - name: Set up Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: 18
    #   - name: Install Dependencies
    #     run: npm install
    #   - name: Run Lint
    #     run: npm run lint